### ISSUE TITLE
Reduce matches for cssFontAttr to just those specified in the W3C spec

### ISSUE THREAD

**Issue by a-vrma** [vim-language-dept/css-syntax.vim#6]
As of now cssFontAttr specifies a lot of font names. However, it doesn't match
_every_ font. This may have made sense back in the day when everyone was only
putting widely available system fonts in their stylesheets, but nowadays it
just makes the values of the `font-family` property look like a confusing
rainbow. Some fonts are highlighted, some aren't.

Rather than try to add the name of every single font to cssFontAttr, I propose
we limit it to the [official W3C aliases](https://www.w3.org/TR/css-fonts-3/#generic-font-families): `serif`, `sans-serif`, `monospace`,
`fantasy`, and `cursive`.

**Comment by jsit** [comment]
100% agree, thanks! Will update this.

**Comment by a-vrma** [comment]
Also the current matching logic will highlight 'serif' inside another font's name. For example 'Charter-serif' will have the last part highlighted.
